#!/bin/bash

echo 'Checking for required tools... '
command -v jade  >/dev/null 2>&1 || { echo 'Install jade and markdown: npm install -g jade markdown' >&2; exit 1; }
command -v lessc >/dev/null 2>&1 || { echo 'Install less: npm install -g less' >&2; exit 1; }
command -v snockets >/dev/null 2>&1 || { echo 'Install snockets: npm install -g snockets-cli' >&2; exit 1; }

echo 'Checking for required source files... '
if [ ! -f ./xml/indesign.xml ]; then
  echo './xml/indesign.xml does not exist'
  exit 1
fi

if [ ! -f ./xml/illustrator.xml ]; then
  echo './xml/illustrator.xml does not exist'
  exit 1
fi

if [ ! -f ./xml/photoshop.xml ]; then
  echo './xml/photoshop.xml does not exist'
  exit 1
fi

if [ ! -f ./xml/javascript.xml ]; then
  echo './xml/javascript.xml does not exist'
  exit 1
fi

if [ ! -f ./xml/scriptui.xml ]; then
  echo './xml/scriptui.xml does not exist'
  exit 1
fi

if [ ! -d ./node_modules ]; then
  echo 'Installing node_modules... '
  # npm install >/dev/null 2>&1
fi

echo 'Removing stale baked goods...'
./clean

echo 'Generating documentation source files...'
mkdir -p ./docs/source/InDesign/classes
mkdir -p ./docs/source/Illustrator/classes
mkdir -p ./docs/source/Photoshop/classes
mkdir -p ./docs/source/Javascript/classes
mkdir -p ./docs/source/ScriptUI/classes
mkdir -p ./lib/InDesign
mkdir -p ./lib/Illustrator
mkdir -p ./lib/Photoshop
mkdir -p ./lib/Javascript
mkdir -p ./lib/ScriptUI

# bake
node bake.js

echo 'Baking docs/ folder into html/...'
mkdir -p ./html/js
mkdir -p ./html/css
mkdir -p ./html/source/classes
mkdir -p ./html/templates

# html
jade -P -o ./html ./docs/index.jade
jade -P -o ./html/templates ./docs/templates/*.jade

mv ./html/index.html ./html/preprocessed.html
cat ./html/preprocessed.html | sed "s/\.less/\.css/" > ./html/index.html
rm ./html/preprocessed.html

# css
lessc ./docs/css/style.less ./html/css/style.css
cp ./docs/css/bootstrap.css ./html/css/bootstrap.css

# snockets
snockets ./docs/js/main.js -o ./html/js/preprocessed.js
cat ./html/js/preprocessed.js | sed "s/\.jade/\.html/" > ./html/js/main.js
rm ./html/js/preprocessed.js

# source
cp -R ./docs/source ./html

echo 'Compressing docs into zip file...'
zip -q -r ./html/ybm-esapi-docs.zip html

echo 'Done. Enjoy some freshly baked docs. :)'
exit 0;

